apiVersion: v1
kind: ConfigMap
metadata:
  name: batch-processing
  namespace: {{ .Release.Namespace }}
data:
  DEPLOY_MODE: "KUBERNETES_ONPREM"
  MEMORY: {{ .Values.java.memory | quote }}
  REPLICA: "1"
  ISOLATED_REPLICA: "0"
  MONGO_READ_PREF_NAME: "secondary"
  MONGO_READ_PREF_TAGS: "nodeType=ANALYTICS"
  MONGO_INDEX_MANAGER_MODE: "MANUAL"
  EVEMTS_MONGO_INDEX_MANAGER_MODE: "MANUAL"
  GOOGLE_CREDENTIALS_PATH: "/opt/harness/svc/ce_batch_gcp_credentials.json"
  CE_GCP_CREDENTIALS_PATH: "/opt/harness/svc/ce_batch_gcp_credentials.json"
  GOOGLE_APPLICATION_CREDENTIALS: "/opt/harness/svc/ce_gcp_home_project_creds.json"
  S3_SYNC_CONFIG_BUCKET_NAME: {{ .Values.cloudProviderConfig.S3_SYNC_CONFIG_BUCKET_NAME  | quote}}
  S3_SYNC_CONFIG_REGION: {{ .Values.cloudProviderConfig.S3_SYNC_CONFIG_REGION  | quote}}
  UI_SERVER_URL: {{.Values.global.loadbalancerURL}}
  SEGMENT_ENABLED: "false"
  ANOMALY_DETECTION_PYTHON_SERVICE_URL: "http://ce-anomaly-detection.{{ .Release.Namespace }}.svc.cluster.local:8081"
  ANOMALY_DETECTION_USE_PROPHET: "true"
  BANZAI_CONFIG_HOST: "http://ce-cloud-info.{{ .Release.Namespace }}.svc.cluster.local"
  BANZAI_CONFIG_PORT: "8082"
  METRICS_COLLECTION_DISABLED: "true"
  BANZAI_RECOMMENDER_BASEURL: "http://telescopes.{{ .Release.Namespace }}.svc.cluster.local:9090/"
  NG_MANAGER_SERVICE_HTTP_CLIENT_CONFIG_BASE_URL: "http://ng-manager.{{ .Release.Namespace }}.svc.cluster.local:7090/"
  CE_NG_SERVICE_HTTP_CLIENT_CONFIG_BASE_URL: "http://nextgen-ce.{{ .Release.Namespace }}.svc.cluster.local:6340/"
  CONNECTOR_HEALTH_UPDATE_CRON: "0 0 10 * * ?"
  GCP_PROJECT_ID: {{ .Values.cloudProviderConfig.GCP_PROJECT_ID  | quote}}
  SMTP_HOST: {{ .Values.smtp.host | quote}}
  SMTP_USERNAME: {{ .Values.smtp.user | quote}}
  SMTP_PASSWORD: {{ .Values.smtp.password | quote}}
  CLUSTER_DATA_GCS_BUCKET: {{ .Values.cloudProviderConfig.CLUSTER_DATA_GCS_BUCKET  | quote}}
  CLUSTER_DATA_GCS_BACKUP_BUCKET: {{ .Values.cloudProviderConfig.CLUSTER_DATA_GCS_BACKUP_BUCKET  | quote}}
  GCP_USE_NEW_PIPELINE: "true"
  AWS_USE_NEW_PIPELINE: "true"
  GCP_SYNC_ENABLED: "true"
  CONNECTOR_HEALTH_UPDATE_JOB_ENABLED: "true"
  DATA_PIPELINE_CONFIG_GCP_PROJECT_ID: {{ .Values.cloudProviderConfig.GCP_PROJECT_ID  | quote}}
  DATA_PIPELINE_CONFIG_GCS_BASE_PATH: {{ .Values.cloudProviderConfig.DATA_PIPELINE_CONFIG_GCS_BASE_PATH  | quote}}
  STACK_DRIVER_LOGGING_ENABLED: "false"
  NEXT_GEN_MANAGER_SECRET: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
  CE_NG_SERVICE_SECRET: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
